all:
		rm -rf work
			clear
				vlib work
					vlog -sv super.sv && vsim super_ex -c -do "run -all;quit;"

compile:
			vlib work
					vlog -sv super.sv

simulate:
			vsim super_ex -l super.log -c -do "run -all;quit;"

clear:
			
						rm -rf work
									clear
